language: php
php:
  - '5.6'
  - '7.0'

dist: trusty

sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - mysql

env:
 - TRAVIS_HOST=127.0.0.1 TRAVIS_USER=root TRAVIS_PASSWORD=""

before_script:
  - mysql -u root -e 'create database addressable_test;'
  - composer self-update
  - composer install --no-interaction

script:
 - vendor/bin/phpunit

notifications:
  on_success: never
  on_failure: always